#### Небольшое задание

- Создайте объект DataFrame и заполните его значениями площадей (в кв.км.) и количеством населения нескольких (не менеее пяти) областей РФ (данные можно брать из открытых источников, например из википедии);
- Рассчитайте плотность населения по каждой области и занесите эти данные в дополнительный столбец созданного вами объекта DataFrame;
- Опробуйте все методы индексирования и создания срезов для объектов DataFrame, которые мы обсудили в данном разделе.

In [1]:
import numpy as np
import pandas as pd

In [ ]:
population_dict = {'Moscow': 13364800,
                   'Novosibirsk': 1637266,
                   'Vladivostok': 610628,
                   'Omsk': 1101367,
                   'Tomsk': 544566,
                   'Irkutsk': 605708}

population = pd.Series(population_dict)
area_dict = {'Moscow': 2561,
             'Novosibirsk': 502.7,
             'Vladivostok': 561.5,
             'Omsk': 583.3,
             'Tomsk': 295.1,
             'Irkutsk': 280}
area = pd.Series(area_dict)

cities = pd.DataFrame({'population': population,
                       'area': area})
cities['density'] = cities['population'] / cities['area']
cities

             population    area      density
Moscow         13364800  2561.0  5218.586490
Novosibirsk     1637266   502.7  3256.944500
Vladivostok      610628   561.5  1087.494212
Omsk            1101367   583.3  1888.165609
Tomsk            544566   295.1  1845.360895
Irkutsk          605708   280.0  2163.242857

Методы индексирования:

In [10]:
cities['population']

Moscow         13364800
Novosibirsk     1637266
Vladivostok      610628
Omsk            1101367
Tomsk            544566
Irkutsk          605708
Name: population, dtype: int64

In [12]:
cities.area

Moscow         2561.0
Novosibirsk     502.7
Vladivostok     561.5
Omsk            583.3
Tomsk           295.1
Irkutsk         280.0
Name: area, dtype: float64

In [31]:
cities.values[0]

array([1.33648000e+07, 2.56100000e+03, 5.21858649e+03])

In [30]:
cities[:3]

             population    area      density
Moscow         13364800  2561.0  5218.586490
Novosibirsk     1637266   502.7  3256.944500
Vladivostok      610628   561.5  1087.494212

In [15]:
cities[cities['density'] > 2000]

             population    area      density
Moscow         13364800  2561.0  5218.586490
Novosibirsk     1637266   502.7  3256.944500
Irkutsk          605708   280.0  2163.242857

In [25]:
cities.iloc[2]

population    610628.000000
area             561.500000
density         1087.494212
Name: Vladivostok, dtype: float64

In [28]:
cities.iloc[:3, :2]

             population    area
Moscow         13364800  2561.0
Novosibirsk     1637266   502.7
Vladivostok      610628   561.5

In [26]:
cities.loc['Omsk', 'density']

np.float64(1888.1656094633981)

In [27]:
cities.loc['Novosibirsk':'Tomsk', :'area']

             population   area
Novosibirsk     1637266  502.7
Vladivostok      610628  561.5
Omsk            1101367  583.3
Tomsk            544566  295.1

In [29]:
cities.loc[['Moscow', 'Irkutsk'], ['density', 'population']]

             density  population
Moscow   5218.586490    13364800
Irkutsk  2163.242857      605708

In [ ]:
# вместо ix 
cities.loc[cities.index[:3], :'population']

             population
Moscow         13364800
Novosibirsk     1637266
Vladivostok      610628